sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mlallai/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mlallai/react-test npm test -- --coverage

after_success:
  - docker build -t mlallai/multi-client ./client
  - docker build -t mlallai/multi-nginx ./nginx
  - docker build -t mlallai/multi-server ./server
  - docker build -t mlallai/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to Docker Hub
  - docker push mlallai/multi-client
  - docker push mlallai/multi-nginx
  - docker push mlallai/multi-server
  - docker push mlallai/multi-worker
